### ISSUE TITLE
Cuda version mismatch between the requirements and the installed packages. 

### ISSUE THREAD

**Issue by abouelkhair5** [ProvenanceAnalytics/kairos#8]
In the [environment_settings](https://github.com/ProvenanceAnalytics/kairos/blob/main/DARPA/settings/environment-settings.md) file you mention using CUDA version 12.1
However, when you install pytorch and its libraries you use version 11.7
`conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia`
I have tried many many times to get this setup to work 
However, whenever i try to run training for the cadets_E3 dataset I get the following error 
Despite following your environment setup guide to the T when setting up the conda environment
Can you please confirm whether or not the mismatched CUDA versions are intentional?

**Comment by LeMB2A** [comment]
EDITED: I had cuda version 12.3 and faced a similar issue; after installing the mentioned dependencies and running the first cell of _theia3_dataprocess.ipynb,_ the line `from torch_geometric.data import *` has thrown this error
`OSError: [/home/osmanmb/anaconda3/envs/kairos/lib/python3.10/site-packages/torch_sparse/_diag_cuda.so]: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowIlEET_S2_S2_b`. I resolved it by installing version 12.1 of pytorch using `conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia`

**Comment by abouelkhair5** [comment]
I managed to resolve this issue by installing cudatoolkit using conda and reinstalling pytorch-scatter from the link provided and making sure it bypasses the cache
```
conda install cudatoolkit
pip install torch-scatter -f https://data.pyg.org/whl/torch-1.13.0+cu117.html --no-cache-dir
```
